#!/usr/bin/env python3
"""tmp/opt_lap.json (CMA-optimized lap) -> js/ideal-practice.js for Guide & Watch."""
import json
d = json.load(open('tmp/opt_lap.json'))
pts = d['pts']; lap = d['lapTime']
hdr = ("// Auto-generated by the CMA-ES minimum-lap-time solver (tests/cma_opt.mjs).\n"
       "// Optimized racing line + speed plan, verified in the real 240Hz physics: %.2fs\n"
       "// (beats the human reference lap). s=track dist, v=km/h, d=signed lateral offset\n"
       "// (+=right), a=action colour for the floor guide. Source for Guide & Watch modes.\n" % lap)
body = "export const IDEAL_PRACTICE = {\n  track:'practice', car:'gt3rs', lapTime:%.2f,\n  pts:[\n" % lap
for p in pts:
    body += "    {s:%g,v:%g,d:%g,a:'%s'},\n" % (p['s'], round(p['v'],1), round(p['d'],2), p['a'])
body += "  ]\n};\n"
open('js/ideal-practice.js', 'w').write(hdr + body)
import collections
c = collections.Counter(p['a'] for p in pts)
vs = [p['v'] for p in pts]
print(f"wrote js/ideal-practice.js  lap {lap}s  pts={len(pts)}  v[{min(vs):.0f}..{max(vs):.0f}]  actions={dict(c)}")
